version: '3'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
  app:
    image: nis3366_docker-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    ports:
      - "8501:8501"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017